export enum ModulesEnum{
	LOGIN = "LOGIN",
	WEEKS = "WEEKS",
	WEEKGROUPS = "WEEKGROUPS",
	USERS = "USERS",
	ROOT = "ROOT",
	PRESTADORES = "PRESTADORES",
	SERVICIOS = "SERVICIOS",
	VISITS = "VISITS",
}
