export enum VisitTypesEnum {
  PROGRAMACION = 'PROGRAMACION',
  CERTIFICACION = 'CERTIFICACIÓN',
  SOLICITUD = 'SOLICITUD',
  PREVIA = 'PREVIA',
  QUEJA = 'QUEJA',
  REQUERIMIENTO = 'REQUERIMIENTO',
  DERIVADA = 'DERIVADA',
  SEGUIMIENTO = 'SEGUIMIENTO'
} 