export enum VisitStatesEnum {
  VISITA_ESPERA_INICIO = 'VISITA_ESPERA_INICIO',
  VISITA_INICIADA = 'VISITA_INICIADA',
  VISITA_FINALIZADA = 'VISITA_FINALIZADA',
  COMUNICADO_PENDIENTE_VALIDACION = 'COMUNICADO_PENDIENTE_VALIDACION',
  COMUNICADO_PENDIENTE_ENVIO = 'COMUNICADO_PENDIENTE_ENVIO',
  COMUNICADO_ENVIADO = 'COMUNICADO_ENVIADO',
  VISITA_PAUSADA = 'VISITA_PAUSADA',
  INFORME_INICIADO = 'INFORME_INICIADO',
  INFORME_FINALIZADO = 'INFORME_FINALIZADO',
  INFORME_ENVIADO = 'INFORME_ENVIADO',
  COMUNICADO_PENDIENTE_GENERACION = 'COMUNICADO_PENDIENTE_GENERACION',
} 