export enum VisitTypesEnum {
    CERTIFICACION = 'CERTIFICACION',
    PROGRAMACION = 'PROGRAMACION',
    SOLICITUD = 'SOLICITUD',
    PREVIA = 'PREVIA',
    QUEJA = 'QUEJA',
    REQUERIMIENTO = 'REQUERIMIENTO',
    DERIVADA = 'DERIVADA',
    SEGUIMIENTO = 'SEGUIMIENTO'
} 